### ISSUE TITLE
Apple M1 results

### ISSUE THREAD

**Issue by RazrFalcon** [epage/parse-benchmarks-rs#10]
Name | Overhead (release) | Build (debug) | Parse (release) | Downloads | Version
-----|--------------------|---------------|-----------------|-----------|--------
null | 0 KiB | 468ms | 30ms | - | -
chumsky | 646 KiB | 5s | 1s | ![Download count](https://img.shields.io/crates/dr/ariadne) | v0.1.5
combine | 165 KiB | 4s | 685ms | ![Download count](https://img.shields.io/crates/dr/combine) | v3.8.1
nom | 129 KiB | 2s | 733ms | ![Download count](https://img.shields.io/crates/dr/nom) | v7.1.1
peg | 26 KiB | 2s | 15ms | ![Download count](https://img.shields.io/crates/dr/peg) | v0.8.0
pest | 114 KiB | 1s | 637ms | ![Download count](https://img.shields.io/crates/dr/pest) | v2.1.3
pom | 161 KiB | 817ms | 3s | ![Download count](https://img.shields.io/crates/dr/pom) | v3.2.0

*System: Darwin 21.5.0 (arm64) w/ `-j 8`*

Not that different, except pom 👀

**Comment by epage** [comment]
Thanks for sharing!
